export const ROUTES = {
  home: '/',
  aboutUs: '/about-us',
  contacts: '/contacts',
  guarantee: '/guarantee',
  delivery: '/delivery',
  news: '/news',
  feedback: '/feedback',
  tires: '/tires',
  wheels: '/wheels',
  wheelSpacers: '/wheel-spacers',
  searchEmpty: '/products/title',
  search: '/products/title/:title',
  profile: 'profile',
  favorites: 'favorites',
  cart: 'cart',
} as const;
